// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/Path.proto

package buffers.resources;

public final class PathOuterClass {
  private PathOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PathOrBuilder extends
      // @@protoc_insertion_point(interface_extends:buffers.resources.Path)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 id = 2 [(.buffers.gmx) = "GMX_DEPRECATED"];</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 2 [(.buffers.gmx) = "GMX_DEPRECATED"];</code>
     */
    int getId();

    /**
     * <code>optional string background_room_name = 3 [(.buffers.gmx_id) = "backroom"];</code>
     */
    boolean hasBackgroundRoomName();
    /**
     * <code>optional string background_room_name = 3 [(.buffers.gmx_id) = "backroom"];</code>
     */
    java.lang.String getBackgroundRoomName();
    /**
     * <code>optional string background_room_name = 3 [(.buffers.gmx_id) = "backroom"];</code>
     */
    com.google.protobuf.ByteString
        getBackgroundRoomNameBytes();

    /**
     * <code>optional int32 snap_x = 4 [(.buffers.gmx) = "hsnap"];</code>
     */
    boolean hasSnapX();
    /**
     * <code>optional int32 snap_x = 4 [(.buffers.gmx) = "hsnap"];</code>
     */
    int getSnapX();

    /**
     * <code>optional int32 snap_y = 5 [(.buffers.gmx) = "vsnap"];</code>
     */
    boolean hasSnapY();
    /**
     * <code>optional int32 snap_y = 5 [(.buffers.gmx) = "vsnap"];</code>
     */
    int getSnapY();

    /**
     * <code>optional bool smooth = 6 [(.buffers.gmx) = "kind"];</code>
     */
    boolean hasSmooth();
    /**
     * <code>optional bool smooth = 6 [(.buffers.gmx) = "kind"];</code>
     */
    boolean getSmooth();

    /**
     * <code>optional bool closed = 7;</code>
     */
    boolean hasClosed();
    /**
     * <code>optional bool closed = 7;</code>
     */
    boolean getClosed();

    /**
     * <code>optional int32 precision = 8;</code>
     */
    boolean hasPrecision();
    /**
     * <code>optional int32 precision = 8;</code>
     */
    int getPrecision();

    /**
     * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
     */
    java.util.List<buffers.resources.PathOuterClass.Path.Point> 
        getPointsList();
    /**
     * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
     */
    buffers.resources.PathOuterClass.Path.Point getPoints(int index);
    /**
     * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
     */
    int getPointsCount();
    /**
     * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
     */
    java.util.List<? extends buffers.resources.PathOuterClass.Path.PointOrBuilder> 
        getPointsOrBuilderList();
    /**
     * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
     */
    buffers.resources.PathOuterClass.Path.PointOrBuilder getPointsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code buffers.resources.Path}
   */
  public  static final class Path extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:buffers.resources.Path)
      PathOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Path.newBuilder() to construct.
    private Path(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Path() {
      name_ = "";
      id_ = 0;
      backgroundRoomName_ = "";
      snapX_ = 0;
      snapY_ = 0;
      smooth_ = false;
      closed_ = false;
      precision_ = 0;
      points_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Path(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              backgroundRoomName_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              snapX_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              snapY_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              smooth_ = input.readBool();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              closed_ = input.readBool();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              precision_ = input.readInt32();
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                points_ = new java.util.ArrayList<buffers.resources.PathOuterClass.Path.Point>();
                mutable_bitField0_ |= 0x00000100;
              }
              points_.add(
                  input.readMessage(buffers.resources.PathOuterClass.Path.Point.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          points_ = java.util.Collections.unmodifiableList(points_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buffers.resources.PathOuterClass.internal_static_buffers_resources_Path_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buffers.resources.PathOuterClass.internal_static_buffers_resources_Path_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              buffers.resources.PathOuterClass.Path.class, buffers.resources.PathOuterClass.Path.Builder.class);
    }

    public interface PointOrBuilder extends
        // @@protoc_insertion_point(interface_extends:buffers.resources.Path.Point)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 x = 1 [(.buffers.gmx) = "GMX_SPLIT/0"];</code>
       */
      boolean hasX();
      /**
       * <code>optional int32 x = 1 [(.buffers.gmx) = "GMX_SPLIT/0"];</code>
       */
      int getX();

      /**
       * <code>optional int32 y = 2 [(.buffers.gmx) = "GMX_SPLIT/1"];</code>
       */
      boolean hasY();
      /**
       * <code>optional int32 y = 2 [(.buffers.gmx) = "GMX_SPLIT/1"];</code>
       */
      int getY();

      /**
       * <code>optional int32 speed = 3 [(.buffers.gmx) = "GMX_SPLIT/2"];</code>
       */
      boolean hasSpeed();
      /**
       * <code>optional int32 speed = 3 [(.buffers.gmx) = "GMX_SPLIT/2"];</code>
       */
      int getSpeed();
    }
    /**
     * Protobuf type {@code buffers.resources.Path.Point}
     */
    public  static final class Point extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:buffers.resources.Path.Point)
        PointOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Point.newBuilder() to construct.
      private Point(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Point() {
        x_ = 0;
        y_ = 0;
        speed_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Point(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                x_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                y_ = input.readInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                speed_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buffers.resources.PathOuterClass.internal_static_buffers_resources_Path_Point_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buffers.resources.PathOuterClass.internal_static_buffers_resources_Path_Point_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buffers.resources.PathOuterClass.Path.Point.class, buffers.resources.PathOuterClass.Path.Point.Builder.class);
      }

      private int bitField0_;
      public static final int X_FIELD_NUMBER = 1;
      private int x_;
      /**
       * <code>optional int32 x = 1 [(.buffers.gmx) = "GMX_SPLIT/0"];</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 x = 1 [(.buffers.gmx) = "GMX_SPLIT/0"];</code>
       */
      public int getX() {
        return x_;
      }

      public static final int Y_FIELD_NUMBER = 2;
      private int y_;
      /**
       * <code>optional int32 y = 2 [(.buffers.gmx) = "GMX_SPLIT/1"];</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 y = 2 [(.buffers.gmx) = "GMX_SPLIT/1"];</code>
       */
      public int getY() {
        return y_;
      }

      public static final int SPEED_FIELD_NUMBER = 3;
      private int speed_;
      /**
       * <code>optional int32 speed = 3 [(.buffers.gmx) = "GMX_SPLIT/2"];</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 speed = 3 [(.buffers.gmx) = "GMX_SPLIT/2"];</code>
       */
      public int getSpeed() {
        return speed_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, y_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, speed_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, y_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, speed_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof buffers.resources.PathOuterClass.Path.Point)) {
          return super.equals(obj);
        }
        buffers.resources.PathOuterClass.Path.Point other = (buffers.resources.PathOuterClass.Path.Point) obj;

        boolean result = true;
        result = result && (hasX() == other.hasX());
        if (hasX()) {
          result = result && (getX()
              == other.getX());
        }
        result = result && (hasY() == other.hasY());
        if (hasY()) {
          result = result && (getY()
              == other.getY());
        }
        result = result && (hasSpeed() == other.hasSpeed());
        if (hasSpeed()) {
          result = result && (getSpeed()
              == other.getSpeed());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasX()) {
          hash = (37 * hash) + X_FIELD_NUMBER;
          hash = (53 * hash) + getX();
        }
        if (hasY()) {
          hash = (37 * hash) + Y_FIELD_NUMBER;
          hash = (53 * hash) + getY();
        }
        if (hasSpeed()) {
          hash = (37 * hash) + SPEED_FIELD_NUMBER;
          hash = (53 * hash) + getSpeed();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static buffers.resources.PathOuterClass.Path.Point parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static buffers.resources.PathOuterClass.Path.Point parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static buffers.resources.PathOuterClass.Path.Point parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static buffers.resources.PathOuterClass.Path.Point parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static buffers.resources.PathOuterClass.Path.Point parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static buffers.resources.PathOuterClass.Path.Point parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static buffers.resources.PathOuterClass.Path.Point parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static buffers.resources.PathOuterClass.Path.Point parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static buffers.resources.PathOuterClass.Path.Point parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static buffers.resources.PathOuterClass.Path.Point parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static buffers.resources.PathOuterClass.Path.Point parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static buffers.resources.PathOuterClass.Path.Point parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(buffers.resources.PathOuterClass.Path.Point prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code buffers.resources.Path.Point}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:buffers.resources.Path.Point)
          buffers.resources.PathOuterClass.Path.PointOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return buffers.resources.PathOuterClass.internal_static_buffers_resources_Path_Point_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return buffers.resources.PathOuterClass.internal_static_buffers_resources_Path_Point_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  buffers.resources.PathOuterClass.Path.Point.class, buffers.resources.PathOuterClass.Path.Point.Builder.class);
        }

        // Construct using buffers.resources.PathOuterClass.Path.Point.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          x_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          y_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          speed_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return buffers.resources.PathOuterClass.internal_static_buffers_resources_Path_Point_descriptor;
        }

        public buffers.resources.PathOuterClass.Path.Point getDefaultInstanceForType() {
          return buffers.resources.PathOuterClass.Path.Point.getDefaultInstance();
        }

        public buffers.resources.PathOuterClass.Path.Point build() {
          buffers.resources.PathOuterClass.Path.Point result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public buffers.resources.PathOuterClass.Path.Point buildPartial() {
          buffers.resources.PathOuterClass.Path.Point result = new buffers.resources.PathOuterClass.Path.Point(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.x_ = x_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.y_ = y_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.speed_ = speed_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof buffers.resources.PathOuterClass.Path.Point) {
            return mergeFrom((buffers.resources.PathOuterClass.Path.Point)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(buffers.resources.PathOuterClass.Path.Point other) {
          if (other == buffers.resources.PathOuterClass.Path.Point.getDefaultInstance()) return this;
          if (other.hasX()) {
            setX(other.getX());
          }
          if (other.hasY()) {
            setY(other.getY());
          }
          if (other.hasSpeed()) {
            setSpeed(other.getSpeed());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          buffers.resources.PathOuterClass.Path.Point parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (buffers.resources.PathOuterClass.Path.Point) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int x_ ;
        /**
         * <code>optional int32 x = 1 [(.buffers.gmx) = "GMX_SPLIT/0"];</code>
         */
        public boolean hasX() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 x = 1 [(.buffers.gmx) = "GMX_SPLIT/0"];</code>
         */
        public int getX() {
          return x_;
        }
        /**
         * <code>optional int32 x = 1 [(.buffers.gmx) = "GMX_SPLIT/0"];</code>
         */
        public Builder setX(int value) {
          bitField0_ |= 0x00000001;
          x_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 x = 1 [(.buffers.gmx) = "GMX_SPLIT/0"];</code>
         */
        public Builder clearX() {
          bitField0_ = (bitField0_ & ~0x00000001);
          x_ = 0;
          onChanged();
          return this;
        }

        private int y_ ;
        /**
         * <code>optional int32 y = 2 [(.buffers.gmx) = "GMX_SPLIT/1"];</code>
         */
        public boolean hasY() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int32 y = 2 [(.buffers.gmx) = "GMX_SPLIT/1"];</code>
         */
        public int getY() {
          return y_;
        }
        /**
         * <code>optional int32 y = 2 [(.buffers.gmx) = "GMX_SPLIT/1"];</code>
         */
        public Builder setY(int value) {
          bitField0_ |= 0x00000002;
          y_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 y = 2 [(.buffers.gmx) = "GMX_SPLIT/1"];</code>
         */
        public Builder clearY() {
          bitField0_ = (bitField0_ & ~0x00000002);
          y_ = 0;
          onChanged();
          return this;
        }

        private int speed_ ;
        /**
         * <code>optional int32 speed = 3 [(.buffers.gmx) = "GMX_SPLIT/2"];</code>
         */
        public boolean hasSpeed() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int32 speed = 3 [(.buffers.gmx) = "GMX_SPLIT/2"];</code>
         */
        public int getSpeed() {
          return speed_;
        }
        /**
         * <code>optional int32 speed = 3 [(.buffers.gmx) = "GMX_SPLIT/2"];</code>
         */
        public Builder setSpeed(int value) {
          bitField0_ |= 0x00000004;
          speed_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 speed = 3 [(.buffers.gmx) = "GMX_SPLIT/2"];</code>
         */
        public Builder clearSpeed() {
          bitField0_ = (bitField0_ & ~0x00000004);
          speed_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:buffers.resources.Path.Point)
      }

      // @@protoc_insertion_point(class_scope:buffers.resources.Path.Point)
      private static final buffers.resources.PathOuterClass.Path.Point DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new buffers.resources.PathOuterClass.Path.Point();
      }

      public static buffers.resources.PathOuterClass.Path.Point getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Point>
          PARSER = new com.google.protobuf.AbstractParser<Point>() {
        public Point parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Point(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Point> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Point> getParserForType() {
        return PARSER;
      }

      public buffers.resources.PathOuterClass.Path.Point getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional int32 id = 2 [(.buffers.gmx) = "GMX_DEPRECATED"];</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 id = 2 [(.buffers.gmx) = "GMX_DEPRECATED"];</code>
     */
    public int getId() {
      return id_;
    }

    public static final int BACKGROUND_ROOM_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object backgroundRoomName_;
    /**
     * <code>optional string background_room_name = 3 [(.buffers.gmx_id) = "backroom"];</code>
     */
    public boolean hasBackgroundRoomName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string background_room_name = 3 [(.buffers.gmx_id) = "backroom"];</code>
     */
    public java.lang.String getBackgroundRoomName() {
      java.lang.Object ref = backgroundRoomName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          backgroundRoomName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string background_room_name = 3 [(.buffers.gmx_id) = "backroom"];</code>
     */
    public com.google.protobuf.ByteString
        getBackgroundRoomNameBytes() {
      java.lang.Object ref = backgroundRoomName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        backgroundRoomName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SNAP_X_FIELD_NUMBER = 4;
    private int snapX_;
    /**
     * <code>optional int32 snap_x = 4 [(.buffers.gmx) = "hsnap"];</code>
     */
    public boolean hasSnapX() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 snap_x = 4 [(.buffers.gmx) = "hsnap"];</code>
     */
    public int getSnapX() {
      return snapX_;
    }

    public static final int SNAP_Y_FIELD_NUMBER = 5;
    private int snapY_;
    /**
     * <code>optional int32 snap_y = 5 [(.buffers.gmx) = "vsnap"];</code>
     */
    public boolean hasSnapY() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 snap_y = 5 [(.buffers.gmx) = "vsnap"];</code>
     */
    public int getSnapY() {
      return snapY_;
    }

    public static final int SMOOTH_FIELD_NUMBER = 6;
    private boolean smooth_;
    /**
     * <code>optional bool smooth = 6 [(.buffers.gmx) = "kind"];</code>
     */
    public boolean hasSmooth() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool smooth = 6 [(.buffers.gmx) = "kind"];</code>
     */
    public boolean getSmooth() {
      return smooth_;
    }

    public static final int CLOSED_FIELD_NUMBER = 7;
    private boolean closed_;
    /**
     * <code>optional bool closed = 7;</code>
     */
    public boolean hasClosed() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool closed = 7;</code>
     */
    public boolean getClosed() {
      return closed_;
    }

    public static final int PRECISION_FIELD_NUMBER = 8;
    private int precision_;
    /**
     * <code>optional int32 precision = 8;</code>
     */
    public boolean hasPrecision() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 precision = 8;</code>
     */
    public int getPrecision() {
      return precision_;
    }

    public static final int POINTS_FIELD_NUMBER = 9;
    private java.util.List<buffers.resources.PathOuterClass.Path.Point> points_;
    /**
     * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
     */
    public java.util.List<buffers.resources.PathOuterClass.Path.Point> getPointsList() {
      return points_;
    }
    /**
     * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
     */
    public java.util.List<? extends buffers.resources.PathOuterClass.Path.PointOrBuilder> 
        getPointsOrBuilderList() {
      return points_;
    }
    /**
     * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
     */
    public int getPointsCount() {
      return points_.size();
    }
    /**
     * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
     */
    public buffers.resources.PathOuterClass.Path.Point getPoints(int index) {
      return points_.get(index);
    }
    /**
     * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
     */
    public buffers.resources.PathOuterClass.Path.PointOrBuilder getPointsOrBuilder(
        int index) {
      return points_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, backgroundRoomName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, snapX_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, snapY_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, smooth_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, closed_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, precision_);
      }
      for (int i = 0; i < points_.size(); i++) {
        output.writeMessage(9, points_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, backgroundRoomName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, snapX_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, snapY_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, smooth_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, closed_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, precision_);
      }
      for (int i = 0; i < points_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, points_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof buffers.resources.PathOuterClass.Path)) {
        return super.equals(obj);
      }
      buffers.resources.PathOuterClass.Path other = (buffers.resources.PathOuterClass.Path) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasBackgroundRoomName() == other.hasBackgroundRoomName());
      if (hasBackgroundRoomName()) {
        result = result && getBackgroundRoomName()
            .equals(other.getBackgroundRoomName());
      }
      result = result && (hasSnapX() == other.hasSnapX());
      if (hasSnapX()) {
        result = result && (getSnapX()
            == other.getSnapX());
      }
      result = result && (hasSnapY() == other.hasSnapY());
      if (hasSnapY()) {
        result = result && (getSnapY()
            == other.getSnapY());
      }
      result = result && (hasSmooth() == other.hasSmooth());
      if (hasSmooth()) {
        result = result && (getSmooth()
            == other.getSmooth());
      }
      result = result && (hasClosed() == other.hasClosed());
      if (hasClosed()) {
        result = result && (getClosed()
            == other.getClosed());
      }
      result = result && (hasPrecision() == other.hasPrecision());
      if (hasPrecision()) {
        result = result && (getPrecision()
            == other.getPrecision());
      }
      result = result && getPointsList()
          .equals(other.getPointsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasBackgroundRoomName()) {
        hash = (37 * hash) + BACKGROUND_ROOM_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getBackgroundRoomName().hashCode();
      }
      if (hasSnapX()) {
        hash = (37 * hash) + SNAP_X_FIELD_NUMBER;
        hash = (53 * hash) + getSnapX();
      }
      if (hasSnapY()) {
        hash = (37 * hash) + SNAP_Y_FIELD_NUMBER;
        hash = (53 * hash) + getSnapY();
      }
      if (hasSmooth()) {
        hash = (37 * hash) + SMOOTH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getSmooth());
      }
      if (hasClosed()) {
        hash = (37 * hash) + CLOSED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getClosed());
      }
      if (hasPrecision()) {
        hash = (37 * hash) + PRECISION_FIELD_NUMBER;
        hash = (53 * hash) + getPrecision();
      }
      if (getPointsCount() > 0) {
        hash = (37 * hash) + POINTS_FIELD_NUMBER;
        hash = (53 * hash) + getPointsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static buffers.resources.PathOuterClass.Path parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buffers.resources.PathOuterClass.Path parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buffers.resources.PathOuterClass.Path parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buffers.resources.PathOuterClass.Path parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buffers.resources.PathOuterClass.Path parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buffers.resources.PathOuterClass.Path parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buffers.resources.PathOuterClass.Path parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buffers.resources.PathOuterClass.Path parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static buffers.resources.PathOuterClass.Path parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static buffers.resources.PathOuterClass.Path parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static buffers.resources.PathOuterClass.Path parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buffers.resources.PathOuterClass.Path parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(buffers.resources.PathOuterClass.Path prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code buffers.resources.Path}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:buffers.resources.Path)
        buffers.resources.PathOuterClass.PathOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buffers.resources.PathOuterClass.internal_static_buffers_resources_Path_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buffers.resources.PathOuterClass.internal_static_buffers_resources_Path_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buffers.resources.PathOuterClass.Path.class, buffers.resources.PathOuterClass.Path.Builder.class);
      }

      // Construct using buffers.resources.PathOuterClass.Path.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPointsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        backgroundRoomName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        snapX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        snapY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        smooth_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        closed_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        precision_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        if (pointsBuilder_ == null) {
          points_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          pointsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buffers.resources.PathOuterClass.internal_static_buffers_resources_Path_descriptor;
      }

      public buffers.resources.PathOuterClass.Path getDefaultInstanceForType() {
        return buffers.resources.PathOuterClass.Path.getDefaultInstance();
      }

      public buffers.resources.PathOuterClass.Path build() {
        buffers.resources.PathOuterClass.Path result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public buffers.resources.PathOuterClass.Path buildPartial() {
        buffers.resources.PathOuterClass.Path result = new buffers.resources.PathOuterClass.Path(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.backgroundRoomName_ = backgroundRoomName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.snapX_ = snapX_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.snapY_ = snapY_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.smooth_ = smooth_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.closed_ = closed_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.precision_ = precision_;
        if (pointsBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            points_ = java.util.Collections.unmodifiableList(points_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.points_ = points_;
        } else {
          result.points_ = pointsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buffers.resources.PathOuterClass.Path) {
          return mergeFrom((buffers.resources.PathOuterClass.Path)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(buffers.resources.PathOuterClass.Path other) {
        if (other == buffers.resources.PathOuterClass.Path.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasBackgroundRoomName()) {
          bitField0_ |= 0x00000004;
          backgroundRoomName_ = other.backgroundRoomName_;
          onChanged();
        }
        if (other.hasSnapX()) {
          setSnapX(other.getSnapX());
        }
        if (other.hasSnapY()) {
          setSnapY(other.getSnapY());
        }
        if (other.hasSmooth()) {
          setSmooth(other.getSmooth());
        }
        if (other.hasClosed()) {
          setClosed(other.getClosed());
        }
        if (other.hasPrecision()) {
          setPrecision(other.getPrecision());
        }
        if (pointsBuilder_ == null) {
          if (!other.points_.isEmpty()) {
            if (points_.isEmpty()) {
              points_ = other.points_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensurePointsIsMutable();
              points_.addAll(other.points_);
            }
            onChanged();
          }
        } else {
          if (!other.points_.isEmpty()) {
            if (pointsBuilder_.isEmpty()) {
              pointsBuilder_.dispose();
              pointsBuilder_ = null;
              points_ = other.points_;
              bitField0_ = (bitField0_ & ~0x00000100);
              pointsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPointsFieldBuilder() : null;
            } else {
              pointsBuilder_.addAllMessages(other.points_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        buffers.resources.PathOuterClass.Path parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (buffers.resources.PathOuterClass.Path) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 2 [(.buffers.gmx) = "GMX_DEPRECATED"];</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 id = 2 [(.buffers.gmx) = "GMX_DEPRECATED"];</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 2 [(.buffers.gmx) = "GMX_DEPRECATED"];</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 2 [(.buffers.gmx) = "GMX_DEPRECATED"];</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object backgroundRoomName_ = "";
      /**
       * <code>optional string background_room_name = 3 [(.buffers.gmx_id) = "backroom"];</code>
       */
      public boolean hasBackgroundRoomName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string background_room_name = 3 [(.buffers.gmx_id) = "backroom"];</code>
       */
      public java.lang.String getBackgroundRoomName() {
        java.lang.Object ref = backgroundRoomName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            backgroundRoomName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string background_room_name = 3 [(.buffers.gmx_id) = "backroom"];</code>
       */
      public com.google.protobuf.ByteString
          getBackgroundRoomNameBytes() {
        java.lang.Object ref = backgroundRoomName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          backgroundRoomName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string background_room_name = 3 [(.buffers.gmx_id) = "backroom"];</code>
       */
      public Builder setBackgroundRoomName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        backgroundRoomName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string background_room_name = 3 [(.buffers.gmx_id) = "backroom"];</code>
       */
      public Builder clearBackgroundRoomName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        backgroundRoomName_ = getDefaultInstance().getBackgroundRoomName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string background_room_name = 3 [(.buffers.gmx_id) = "backroom"];</code>
       */
      public Builder setBackgroundRoomNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        backgroundRoomName_ = value;
        onChanged();
        return this;
      }

      private int snapX_ ;
      /**
       * <code>optional int32 snap_x = 4 [(.buffers.gmx) = "hsnap"];</code>
       */
      public boolean hasSnapX() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 snap_x = 4 [(.buffers.gmx) = "hsnap"];</code>
       */
      public int getSnapX() {
        return snapX_;
      }
      /**
       * <code>optional int32 snap_x = 4 [(.buffers.gmx) = "hsnap"];</code>
       */
      public Builder setSnapX(int value) {
        bitField0_ |= 0x00000008;
        snapX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 snap_x = 4 [(.buffers.gmx) = "hsnap"];</code>
       */
      public Builder clearSnapX() {
        bitField0_ = (bitField0_ & ~0x00000008);
        snapX_ = 0;
        onChanged();
        return this;
      }

      private int snapY_ ;
      /**
       * <code>optional int32 snap_y = 5 [(.buffers.gmx) = "vsnap"];</code>
       */
      public boolean hasSnapY() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 snap_y = 5 [(.buffers.gmx) = "vsnap"];</code>
       */
      public int getSnapY() {
        return snapY_;
      }
      /**
       * <code>optional int32 snap_y = 5 [(.buffers.gmx) = "vsnap"];</code>
       */
      public Builder setSnapY(int value) {
        bitField0_ |= 0x00000010;
        snapY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 snap_y = 5 [(.buffers.gmx) = "vsnap"];</code>
       */
      public Builder clearSnapY() {
        bitField0_ = (bitField0_ & ~0x00000010);
        snapY_ = 0;
        onChanged();
        return this;
      }

      private boolean smooth_ ;
      /**
       * <code>optional bool smooth = 6 [(.buffers.gmx) = "kind"];</code>
       */
      public boolean hasSmooth() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bool smooth = 6 [(.buffers.gmx) = "kind"];</code>
       */
      public boolean getSmooth() {
        return smooth_;
      }
      /**
       * <code>optional bool smooth = 6 [(.buffers.gmx) = "kind"];</code>
       */
      public Builder setSmooth(boolean value) {
        bitField0_ |= 0x00000020;
        smooth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool smooth = 6 [(.buffers.gmx) = "kind"];</code>
       */
      public Builder clearSmooth() {
        bitField0_ = (bitField0_ & ~0x00000020);
        smooth_ = false;
        onChanged();
        return this;
      }

      private boolean closed_ ;
      /**
       * <code>optional bool closed = 7;</code>
       */
      public boolean hasClosed() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool closed = 7;</code>
       */
      public boolean getClosed() {
        return closed_;
      }
      /**
       * <code>optional bool closed = 7;</code>
       */
      public Builder setClosed(boolean value) {
        bitField0_ |= 0x00000040;
        closed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool closed = 7;</code>
       */
      public Builder clearClosed() {
        bitField0_ = (bitField0_ & ~0x00000040);
        closed_ = false;
        onChanged();
        return this;
      }

      private int precision_ ;
      /**
       * <code>optional int32 precision = 8;</code>
       */
      public boolean hasPrecision() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 precision = 8;</code>
       */
      public int getPrecision() {
        return precision_;
      }
      /**
       * <code>optional int32 precision = 8;</code>
       */
      public Builder setPrecision(int value) {
        bitField0_ |= 0x00000080;
        precision_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 precision = 8;</code>
       */
      public Builder clearPrecision() {
        bitField0_ = (bitField0_ & ~0x00000080);
        precision_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<buffers.resources.PathOuterClass.Path.Point> points_ =
        java.util.Collections.emptyList();
      private void ensurePointsIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          points_ = new java.util.ArrayList<buffers.resources.PathOuterClass.Path.Point>(points_);
          bitField0_ |= 0x00000100;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          buffers.resources.PathOuterClass.Path.Point, buffers.resources.PathOuterClass.Path.Point.Builder, buffers.resources.PathOuterClass.Path.PointOrBuilder> pointsBuilder_;

      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public java.util.List<buffers.resources.PathOuterClass.Path.Point> getPointsList() {
        if (pointsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(points_);
        } else {
          return pointsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public int getPointsCount() {
        if (pointsBuilder_ == null) {
          return points_.size();
        } else {
          return pointsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public buffers.resources.PathOuterClass.Path.Point getPoints(int index) {
        if (pointsBuilder_ == null) {
          return points_.get(index);
        } else {
          return pointsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public Builder setPoints(
          int index, buffers.resources.PathOuterClass.Path.Point value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.set(index, value);
          onChanged();
        } else {
          pointsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public Builder setPoints(
          int index, buffers.resources.PathOuterClass.Path.Point.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.set(index, builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public Builder addPoints(buffers.resources.PathOuterClass.Path.Point value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.add(value);
          onChanged();
        } else {
          pointsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public Builder addPoints(
          int index, buffers.resources.PathOuterClass.Path.Point value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.add(index, value);
          onChanged();
        } else {
          pointsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public Builder addPoints(
          buffers.resources.PathOuterClass.Path.Point.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.add(builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public Builder addPoints(
          int index, buffers.resources.PathOuterClass.Path.Point.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.add(index, builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public Builder addAllPoints(
          java.lang.Iterable<? extends buffers.resources.PathOuterClass.Path.Point> values) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, points_);
          onChanged();
        } else {
          pointsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public Builder clearPoints() {
        if (pointsBuilder_ == null) {
          points_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          pointsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public Builder removePoints(int index) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.remove(index);
          onChanged();
        } else {
          pointsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public buffers.resources.PathOuterClass.Path.Point.Builder getPointsBuilder(
          int index) {
        return getPointsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public buffers.resources.PathOuterClass.Path.PointOrBuilder getPointsOrBuilder(
          int index) {
        if (pointsBuilder_ == null) {
          return points_.get(index);  } else {
          return pointsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public java.util.List<? extends buffers.resources.PathOuterClass.Path.PointOrBuilder> 
           getPointsOrBuilderList() {
        if (pointsBuilder_ != null) {
          return pointsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(points_);
        }
      }
      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public buffers.resources.PathOuterClass.Path.Point.Builder addPointsBuilder() {
        return getPointsFieldBuilder().addBuilder(
            buffers.resources.PathOuterClass.Path.Point.getDefaultInstance());
      }
      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public buffers.resources.PathOuterClass.Path.Point.Builder addPointsBuilder(
          int index) {
        return getPointsFieldBuilder().addBuilder(
            index, buffers.resources.PathOuterClass.Path.Point.getDefaultInstance());
      }
      /**
       * <code>repeated .buffers.resources.Path.Point points = 9 [(.buffers.gmx) = "points/point"];</code>
       */
      public java.util.List<buffers.resources.PathOuterClass.Path.Point.Builder> 
           getPointsBuilderList() {
        return getPointsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          buffers.resources.PathOuterClass.Path.Point, buffers.resources.PathOuterClass.Path.Point.Builder, buffers.resources.PathOuterClass.Path.PointOrBuilder> 
          getPointsFieldBuilder() {
        if (pointsBuilder_ == null) {
          pointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              buffers.resources.PathOuterClass.Path.Point, buffers.resources.PathOuterClass.Path.Point.Builder, buffers.resources.PathOuterClass.Path.PointOrBuilder>(
                  points_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          points_ = null;
        }
        return pointsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:buffers.resources.Path)
    }

    // @@protoc_insertion_point(class_scope:buffers.resources.Path)
    private static final buffers.resources.PathOuterClass.Path DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new buffers.resources.PathOuterClass.Path();
    }

    public static buffers.resources.PathOuterClass.Path getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Path>
        PARSER = new com.google.protobuf.AbstractParser<Path>() {
      public Path parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Path(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Path> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Path> getParserForType() {
      return PARSER;
    }

    public buffers.resources.PathOuterClass.Path getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buffers_resources_Path_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buffers_resources_Path_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buffers_resources_Path_Point_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buffers_resources_Path_Point_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024resources/Path.proto\022\021buffers.resource" +
      "s\032\roptions.proto\"\365\002\n\004Path\022\014\n\004name\030\001 \001(\t\022" +
      "\036\n\002id\030\002 \001(\005B\022\202\265\030\016GMX_DEPRECATED\022*\n\024backg" +
      "round_room_name\030\003 \001(\tB\014\212\265\030\010backroom\022\031\n\006s" +
      "nap_x\030\004 \001(\005B\t\202\265\030\005hsnap\022\031\n\006snap_y\030\005 \001(\005B\t" +
      "\202\265\030\005vsnap\022\030\n\006smooth\030\006 \001(\010B\010\202\265\030\004kind\022\016\n\006c" +
      "losed\030\007 \001(\010\022\021\n\tprecision\030\010 \001(\005\022?\n\006points" +
      "\030\t \003(\0132\035.buffers.resources.Path.PointB\020\202" +
      "\265\030\014points/point\032_\n\005Point\022\032\n\001x\030\001 \001(\005B\017\202\265\030" +
      "\013GMX_SPLIT/0\022\032\n\001y\030\002 \001(\005B\017\202\265\030\013GMX_SPLIT/1" +
      "\022\036\n\005speed\030\003 \001(\005B\017\202\265\030\013GMX_SPLIT/2"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          buffers.Options.getDescriptor(),
        }, assigner);
    internal_static_buffers_resources_Path_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_buffers_resources_Path_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buffers_resources_Path_descriptor,
        new java.lang.String[] { "Name", "Id", "BackgroundRoomName", "SnapX", "SnapY", "Smooth", "Closed", "Precision", "Points", });
    internal_static_buffers_resources_Path_Point_descriptor =
      internal_static_buffers_resources_Path_descriptor.getNestedTypes().get(0);
    internal_static_buffers_resources_Path_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buffers_resources_Path_Point_descriptor,
        new java.lang.String[] { "X", "Y", "Speed", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(buffers.Options.gmx);
    registry.add(buffers.Options.gmxId);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    buffers.Options.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
