// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/Timeline.proto

package buffers.resources;

public final class TimelineOuterClass {
  private TimelineOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TimelineOrBuilder extends
      // @@protoc_insertion_point(interface_extends:buffers.resources.Timeline)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 id = 2 [(.buffers.gmx) = "GMX_DEPRECATED"];</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 2 [(.buffers.gmx) = "GMX_DEPRECATED"];</code>
     */
    int getId();

    /**
     * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
     */
    java.util.List<buffers.resources.TimelineOuterClass.Timeline.Moment> 
        getMomentsList();
    /**
     * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
     */
    buffers.resources.TimelineOuterClass.Timeline.Moment getMoments(int index);
    /**
     * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
     */
    int getMomentsCount();
    /**
     * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
     */
    java.util.List<? extends buffers.resources.TimelineOuterClass.Timeline.MomentOrBuilder> 
        getMomentsOrBuilderList();
    /**
     * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
     */
    buffers.resources.TimelineOuterClass.Timeline.MomentOrBuilder getMomentsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code buffers.resources.Timeline}
   */
  public  static final class Timeline extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:buffers.resources.Timeline)
      TimelineOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Timeline.newBuilder() to construct.
    private Timeline(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Timeline() {
      name_ = "";
      id_ = 0;
      moments_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Timeline(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                moments_ = new java.util.ArrayList<buffers.resources.TimelineOuterClass.Timeline.Moment>();
                mutable_bitField0_ |= 0x00000004;
              }
              moments_.add(
                  input.readMessage(buffers.resources.TimelineOuterClass.Timeline.Moment.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          moments_ = java.util.Collections.unmodifiableList(moments_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buffers.resources.TimelineOuterClass.internal_static_buffers_resources_Timeline_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buffers.resources.TimelineOuterClass.internal_static_buffers_resources_Timeline_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              buffers.resources.TimelineOuterClass.Timeline.class, buffers.resources.TimelineOuterClass.Timeline.Builder.class);
    }

    public interface MomentOrBuilder extends
        // @@protoc_insertion_point(interface_extends:buffers.resources.Timeline.Moment)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 step = 1;</code>
       */
      boolean hasStep();
      /**
       * <code>optional int32 step = 1;</code>
       */
      int getStep();

      /**
       * <code>optional .buffers.resources.Event event = 2;</code>
       */
      boolean hasEvent();
      /**
       * <code>optional .buffers.resources.Event event = 2;</code>
       */
      buffers.resources.EventOuterClass.Event getEvent();
      /**
       * <code>optional .buffers.resources.Event event = 2;</code>
       */
      buffers.resources.EventOuterClass.EventOrBuilder getEventOrBuilder();
    }
    /**
     * Protobuf type {@code buffers.resources.Timeline.Moment}
     */
    public  static final class Moment extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:buffers.resources.Timeline.Moment)
        MomentOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Moment.newBuilder() to construct.
      private Moment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Moment() {
        step_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Moment(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                step_ = input.readInt32();
                break;
              }
              case 18: {
                buffers.resources.EventOuterClass.Event.Builder subBuilder = null;
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                  subBuilder = event_.toBuilder();
                }
                event_ = input.readMessage(buffers.resources.EventOuterClass.Event.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(event_);
                  event_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000002;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buffers.resources.TimelineOuterClass.internal_static_buffers_resources_Timeline_Moment_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buffers.resources.TimelineOuterClass.internal_static_buffers_resources_Timeline_Moment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buffers.resources.TimelineOuterClass.Timeline.Moment.class, buffers.resources.TimelineOuterClass.Timeline.Moment.Builder.class);
      }

      private int bitField0_;
      public static final int STEP_FIELD_NUMBER = 1;
      private int step_;
      /**
       * <code>optional int32 step = 1;</code>
       */
      public boolean hasStep() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 step = 1;</code>
       */
      public int getStep() {
        return step_;
      }

      public static final int EVENT_FIELD_NUMBER = 2;
      private buffers.resources.EventOuterClass.Event event_;
      /**
       * <code>optional .buffers.resources.Event event = 2;</code>
       */
      public boolean hasEvent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .buffers.resources.Event event = 2;</code>
       */
      public buffers.resources.EventOuterClass.Event getEvent() {
        return event_ == null ? buffers.resources.EventOuterClass.Event.getDefaultInstance() : event_;
      }
      /**
       * <code>optional .buffers.resources.Event event = 2;</code>
       */
      public buffers.resources.EventOuterClass.EventOrBuilder getEventOrBuilder() {
        return event_ == null ? buffers.resources.EventOuterClass.Event.getDefaultInstance() : event_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, step_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeMessage(2, getEvent());
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, step_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, getEvent());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof buffers.resources.TimelineOuterClass.Timeline.Moment)) {
          return super.equals(obj);
        }
        buffers.resources.TimelineOuterClass.Timeline.Moment other = (buffers.resources.TimelineOuterClass.Timeline.Moment) obj;

        boolean result = true;
        result = result && (hasStep() == other.hasStep());
        if (hasStep()) {
          result = result && (getStep()
              == other.getStep());
        }
        result = result && (hasEvent() == other.hasEvent());
        if (hasEvent()) {
          result = result && getEvent()
              .equals(other.getEvent());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasStep()) {
          hash = (37 * hash) + STEP_FIELD_NUMBER;
          hash = (53 * hash) + getStep();
        }
        if (hasEvent()) {
          hash = (37 * hash) + EVENT_FIELD_NUMBER;
          hash = (53 * hash) + getEvent().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static buffers.resources.TimelineOuterClass.Timeline.Moment parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static buffers.resources.TimelineOuterClass.Timeline.Moment parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static buffers.resources.TimelineOuterClass.Timeline.Moment parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static buffers.resources.TimelineOuterClass.Timeline.Moment parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static buffers.resources.TimelineOuterClass.Timeline.Moment parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static buffers.resources.TimelineOuterClass.Timeline.Moment parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static buffers.resources.TimelineOuterClass.Timeline.Moment parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static buffers.resources.TimelineOuterClass.Timeline.Moment parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static buffers.resources.TimelineOuterClass.Timeline.Moment parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static buffers.resources.TimelineOuterClass.Timeline.Moment parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static buffers.resources.TimelineOuterClass.Timeline.Moment parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static buffers.resources.TimelineOuterClass.Timeline.Moment parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(buffers.resources.TimelineOuterClass.Timeline.Moment prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code buffers.resources.Timeline.Moment}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:buffers.resources.Timeline.Moment)
          buffers.resources.TimelineOuterClass.Timeline.MomentOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return buffers.resources.TimelineOuterClass.internal_static_buffers_resources_Timeline_Moment_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return buffers.resources.TimelineOuterClass.internal_static_buffers_resources_Timeline_Moment_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  buffers.resources.TimelineOuterClass.Timeline.Moment.class, buffers.resources.TimelineOuterClass.Timeline.Moment.Builder.class);
        }

        // Construct using buffers.resources.TimelineOuterClass.Timeline.Moment.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
            getEventFieldBuilder();
          }
        }
        public Builder clear() {
          super.clear();
          step_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          if (eventBuilder_ == null) {
            event_ = null;
          } else {
            eventBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return buffers.resources.TimelineOuterClass.internal_static_buffers_resources_Timeline_Moment_descriptor;
        }

        public buffers.resources.TimelineOuterClass.Timeline.Moment getDefaultInstanceForType() {
          return buffers.resources.TimelineOuterClass.Timeline.Moment.getDefaultInstance();
        }

        public buffers.resources.TimelineOuterClass.Timeline.Moment build() {
          buffers.resources.TimelineOuterClass.Timeline.Moment result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public buffers.resources.TimelineOuterClass.Timeline.Moment buildPartial() {
          buffers.resources.TimelineOuterClass.Timeline.Moment result = new buffers.resources.TimelineOuterClass.Timeline.Moment(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.step_ = step_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          if (eventBuilder_ == null) {
            result.event_ = event_;
          } else {
            result.event_ = eventBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof buffers.resources.TimelineOuterClass.Timeline.Moment) {
            return mergeFrom((buffers.resources.TimelineOuterClass.Timeline.Moment)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(buffers.resources.TimelineOuterClass.Timeline.Moment other) {
          if (other == buffers.resources.TimelineOuterClass.Timeline.Moment.getDefaultInstance()) return this;
          if (other.hasStep()) {
            setStep(other.getStep());
          }
          if (other.hasEvent()) {
            mergeEvent(other.getEvent());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          buffers.resources.TimelineOuterClass.Timeline.Moment parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (buffers.resources.TimelineOuterClass.Timeline.Moment) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int step_ ;
        /**
         * <code>optional int32 step = 1;</code>
         */
        public boolean hasStep() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 step = 1;</code>
         */
        public int getStep() {
          return step_;
        }
        /**
         * <code>optional int32 step = 1;</code>
         */
        public Builder setStep(int value) {
          bitField0_ |= 0x00000001;
          step_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 step = 1;</code>
         */
        public Builder clearStep() {
          bitField0_ = (bitField0_ & ~0x00000001);
          step_ = 0;
          onChanged();
          return this;
        }

        private buffers.resources.EventOuterClass.Event event_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
            buffers.resources.EventOuterClass.Event, buffers.resources.EventOuterClass.Event.Builder, buffers.resources.EventOuterClass.EventOrBuilder> eventBuilder_;
        /**
         * <code>optional .buffers.resources.Event event = 2;</code>
         */
        public boolean hasEvent() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional .buffers.resources.Event event = 2;</code>
         */
        public buffers.resources.EventOuterClass.Event getEvent() {
          if (eventBuilder_ == null) {
            return event_ == null ? buffers.resources.EventOuterClass.Event.getDefaultInstance() : event_;
          } else {
            return eventBuilder_.getMessage();
          }
        }
        /**
         * <code>optional .buffers.resources.Event event = 2;</code>
         */
        public Builder setEvent(buffers.resources.EventOuterClass.Event value) {
          if (eventBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            event_ = value;
            onChanged();
          } else {
            eventBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>optional .buffers.resources.Event event = 2;</code>
         */
        public Builder setEvent(
            buffers.resources.EventOuterClass.Event.Builder builderForValue) {
          if (eventBuilder_ == null) {
            event_ = builderForValue.build();
            onChanged();
          } else {
            eventBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>optional .buffers.resources.Event event = 2;</code>
         */
        public Builder mergeEvent(buffers.resources.EventOuterClass.Event value) {
          if (eventBuilder_ == null) {
            if (((bitField0_ & 0x00000002) == 0x00000002) &&
                event_ != null &&
                event_ != buffers.resources.EventOuterClass.Event.getDefaultInstance()) {
              event_ =
                buffers.resources.EventOuterClass.Event.newBuilder(event_).mergeFrom(value).buildPartial();
            } else {
              event_ = value;
            }
            onChanged();
          } else {
            eventBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>optional .buffers.resources.Event event = 2;</code>
         */
        public Builder clearEvent() {
          if (eventBuilder_ == null) {
            event_ = null;
            onChanged();
          } else {
            eventBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        /**
         * <code>optional .buffers.resources.Event event = 2;</code>
         */
        public buffers.resources.EventOuterClass.Event.Builder getEventBuilder() {
          bitField0_ |= 0x00000002;
          onChanged();
          return getEventFieldBuilder().getBuilder();
        }
        /**
         * <code>optional .buffers.resources.Event event = 2;</code>
         */
        public buffers.resources.EventOuterClass.EventOrBuilder getEventOrBuilder() {
          if (eventBuilder_ != null) {
            return eventBuilder_.getMessageOrBuilder();
          } else {
            return event_ == null ?
                buffers.resources.EventOuterClass.Event.getDefaultInstance() : event_;
          }
        }
        /**
         * <code>optional .buffers.resources.Event event = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            buffers.resources.EventOuterClass.Event, buffers.resources.EventOuterClass.Event.Builder, buffers.resources.EventOuterClass.EventOrBuilder> 
            getEventFieldBuilder() {
          if (eventBuilder_ == null) {
            eventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                buffers.resources.EventOuterClass.Event, buffers.resources.EventOuterClass.Event.Builder, buffers.resources.EventOuterClass.EventOrBuilder>(
                    getEvent(),
                    getParentForChildren(),
                    isClean());
            event_ = null;
          }
          return eventBuilder_;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:buffers.resources.Timeline.Moment)
      }

      // @@protoc_insertion_point(class_scope:buffers.resources.Timeline.Moment)
      private static final buffers.resources.TimelineOuterClass.Timeline.Moment DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new buffers.resources.TimelineOuterClass.Timeline.Moment();
      }

      public static buffers.resources.TimelineOuterClass.Timeline.Moment getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Moment>
          PARSER = new com.google.protobuf.AbstractParser<Moment>() {
        public Moment parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Moment(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Moment> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Moment> getParserForType() {
        return PARSER;
      }

      public buffers.resources.TimelineOuterClass.Timeline.Moment getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional int32 id = 2 [(.buffers.gmx) = "GMX_DEPRECATED"];</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 id = 2 [(.buffers.gmx) = "GMX_DEPRECATED"];</code>
     */
    public int getId() {
      return id_;
    }

    public static final int MOMENTS_FIELD_NUMBER = 3;
    private java.util.List<buffers.resources.TimelineOuterClass.Timeline.Moment> moments_;
    /**
     * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
     */
    public java.util.List<buffers.resources.TimelineOuterClass.Timeline.Moment> getMomentsList() {
      return moments_;
    }
    /**
     * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
     */
    public java.util.List<? extends buffers.resources.TimelineOuterClass.Timeline.MomentOrBuilder> 
        getMomentsOrBuilderList() {
      return moments_;
    }
    /**
     * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
     */
    public int getMomentsCount() {
      return moments_.size();
    }
    /**
     * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
     */
    public buffers.resources.TimelineOuterClass.Timeline.Moment getMoments(int index) {
      return moments_.get(index);
    }
    /**
     * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
     */
    public buffers.resources.TimelineOuterClass.Timeline.MomentOrBuilder getMomentsOrBuilder(
        int index) {
      return moments_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      for (int i = 0; i < moments_.size(); i++) {
        output.writeMessage(3, moments_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      for (int i = 0; i < moments_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, moments_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof buffers.resources.TimelineOuterClass.Timeline)) {
        return super.equals(obj);
      }
      buffers.resources.TimelineOuterClass.Timeline other = (buffers.resources.TimelineOuterClass.Timeline) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && getMomentsList()
          .equals(other.getMomentsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (getMomentsCount() > 0) {
        hash = (37 * hash) + MOMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getMomentsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static buffers.resources.TimelineOuterClass.Timeline parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buffers.resources.TimelineOuterClass.Timeline parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buffers.resources.TimelineOuterClass.Timeline parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buffers.resources.TimelineOuterClass.Timeline parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buffers.resources.TimelineOuterClass.Timeline parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static buffers.resources.TimelineOuterClass.Timeline parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static buffers.resources.TimelineOuterClass.Timeline parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buffers.resources.TimelineOuterClass.Timeline parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static buffers.resources.TimelineOuterClass.Timeline parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static buffers.resources.TimelineOuterClass.Timeline parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static buffers.resources.TimelineOuterClass.Timeline parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static buffers.resources.TimelineOuterClass.Timeline parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(buffers.resources.TimelineOuterClass.Timeline prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code buffers.resources.Timeline}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:buffers.resources.Timeline)
        buffers.resources.TimelineOuterClass.TimelineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buffers.resources.TimelineOuterClass.internal_static_buffers_resources_Timeline_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buffers.resources.TimelineOuterClass.internal_static_buffers_resources_Timeline_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                buffers.resources.TimelineOuterClass.Timeline.class, buffers.resources.TimelineOuterClass.Timeline.Builder.class);
      }

      // Construct using buffers.resources.TimelineOuterClass.Timeline.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMomentsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (momentsBuilder_ == null) {
          moments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          momentsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buffers.resources.TimelineOuterClass.internal_static_buffers_resources_Timeline_descriptor;
      }

      public buffers.resources.TimelineOuterClass.Timeline getDefaultInstanceForType() {
        return buffers.resources.TimelineOuterClass.Timeline.getDefaultInstance();
      }

      public buffers.resources.TimelineOuterClass.Timeline build() {
        buffers.resources.TimelineOuterClass.Timeline result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public buffers.resources.TimelineOuterClass.Timeline buildPartial() {
        buffers.resources.TimelineOuterClass.Timeline result = new buffers.resources.TimelineOuterClass.Timeline(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (momentsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            moments_ = java.util.Collections.unmodifiableList(moments_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.moments_ = moments_;
        } else {
          result.moments_ = momentsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buffers.resources.TimelineOuterClass.Timeline) {
          return mergeFrom((buffers.resources.TimelineOuterClass.Timeline)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(buffers.resources.TimelineOuterClass.Timeline other) {
        if (other == buffers.resources.TimelineOuterClass.Timeline.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (momentsBuilder_ == null) {
          if (!other.moments_.isEmpty()) {
            if (moments_.isEmpty()) {
              moments_ = other.moments_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureMomentsIsMutable();
              moments_.addAll(other.moments_);
            }
            onChanged();
          }
        } else {
          if (!other.moments_.isEmpty()) {
            if (momentsBuilder_.isEmpty()) {
              momentsBuilder_.dispose();
              momentsBuilder_ = null;
              moments_ = other.moments_;
              bitField0_ = (bitField0_ & ~0x00000004);
              momentsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMomentsFieldBuilder() : null;
            } else {
              momentsBuilder_.addAllMessages(other.moments_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        buffers.resources.TimelineOuterClass.Timeline parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (buffers.resources.TimelineOuterClass.Timeline) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 2 [(.buffers.gmx) = "GMX_DEPRECATED"];</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 id = 2 [(.buffers.gmx) = "GMX_DEPRECATED"];</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 2 [(.buffers.gmx) = "GMX_DEPRECATED"];</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 2 [(.buffers.gmx) = "GMX_DEPRECATED"];</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<buffers.resources.TimelineOuterClass.Timeline.Moment> moments_ =
        java.util.Collections.emptyList();
      private void ensureMomentsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          moments_ = new java.util.ArrayList<buffers.resources.TimelineOuterClass.Timeline.Moment>(moments_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          buffers.resources.TimelineOuterClass.Timeline.Moment, buffers.resources.TimelineOuterClass.Timeline.Moment.Builder, buffers.resources.TimelineOuterClass.Timeline.MomentOrBuilder> momentsBuilder_;

      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public java.util.List<buffers.resources.TimelineOuterClass.Timeline.Moment> getMomentsList() {
        if (momentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(moments_);
        } else {
          return momentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public int getMomentsCount() {
        if (momentsBuilder_ == null) {
          return moments_.size();
        } else {
          return momentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public buffers.resources.TimelineOuterClass.Timeline.Moment getMoments(int index) {
        if (momentsBuilder_ == null) {
          return moments_.get(index);
        } else {
          return momentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public Builder setMoments(
          int index, buffers.resources.TimelineOuterClass.Timeline.Moment value) {
        if (momentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMomentsIsMutable();
          moments_.set(index, value);
          onChanged();
        } else {
          momentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public Builder setMoments(
          int index, buffers.resources.TimelineOuterClass.Timeline.Moment.Builder builderForValue) {
        if (momentsBuilder_ == null) {
          ensureMomentsIsMutable();
          moments_.set(index, builderForValue.build());
          onChanged();
        } else {
          momentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public Builder addMoments(buffers.resources.TimelineOuterClass.Timeline.Moment value) {
        if (momentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMomentsIsMutable();
          moments_.add(value);
          onChanged();
        } else {
          momentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public Builder addMoments(
          int index, buffers.resources.TimelineOuterClass.Timeline.Moment value) {
        if (momentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMomentsIsMutable();
          moments_.add(index, value);
          onChanged();
        } else {
          momentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public Builder addMoments(
          buffers.resources.TimelineOuterClass.Timeline.Moment.Builder builderForValue) {
        if (momentsBuilder_ == null) {
          ensureMomentsIsMutable();
          moments_.add(builderForValue.build());
          onChanged();
        } else {
          momentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public Builder addMoments(
          int index, buffers.resources.TimelineOuterClass.Timeline.Moment.Builder builderForValue) {
        if (momentsBuilder_ == null) {
          ensureMomentsIsMutable();
          moments_.add(index, builderForValue.build());
          onChanged();
        } else {
          momentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public Builder addAllMoments(
          java.lang.Iterable<? extends buffers.resources.TimelineOuterClass.Timeline.Moment> values) {
        if (momentsBuilder_ == null) {
          ensureMomentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, moments_);
          onChanged();
        } else {
          momentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public Builder clearMoments() {
        if (momentsBuilder_ == null) {
          moments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          momentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public Builder removeMoments(int index) {
        if (momentsBuilder_ == null) {
          ensureMomentsIsMutable();
          moments_.remove(index);
          onChanged();
        } else {
          momentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public buffers.resources.TimelineOuterClass.Timeline.Moment.Builder getMomentsBuilder(
          int index) {
        return getMomentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public buffers.resources.TimelineOuterClass.Timeline.MomentOrBuilder getMomentsOrBuilder(
          int index) {
        if (momentsBuilder_ == null) {
          return moments_.get(index);  } else {
          return momentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public java.util.List<? extends buffers.resources.TimelineOuterClass.Timeline.MomentOrBuilder> 
           getMomentsOrBuilderList() {
        if (momentsBuilder_ != null) {
          return momentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(moments_);
        }
      }
      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public buffers.resources.TimelineOuterClass.Timeline.Moment.Builder addMomentsBuilder() {
        return getMomentsFieldBuilder().addBuilder(
            buffers.resources.TimelineOuterClass.Timeline.Moment.getDefaultInstance());
      }
      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public buffers.resources.TimelineOuterClass.Timeline.Moment.Builder addMomentsBuilder(
          int index) {
        return getMomentsFieldBuilder().addBuilder(
            index, buffers.resources.TimelineOuterClass.Timeline.Moment.getDefaultInstance());
      }
      /**
       * <code>repeated .buffers.resources.Timeline.Moment moments = 3 [(.buffers.gmx) = "entry"];</code>
       */
      public java.util.List<buffers.resources.TimelineOuterClass.Timeline.Moment.Builder> 
           getMomentsBuilderList() {
        return getMomentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          buffers.resources.TimelineOuterClass.Timeline.Moment, buffers.resources.TimelineOuterClass.Timeline.Moment.Builder, buffers.resources.TimelineOuterClass.Timeline.MomentOrBuilder> 
          getMomentsFieldBuilder() {
        if (momentsBuilder_ == null) {
          momentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              buffers.resources.TimelineOuterClass.Timeline.Moment, buffers.resources.TimelineOuterClass.Timeline.Moment.Builder, buffers.resources.TimelineOuterClass.Timeline.MomentOrBuilder>(
                  moments_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          moments_ = null;
        }
        return momentsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:buffers.resources.Timeline)
    }

    // @@protoc_insertion_point(class_scope:buffers.resources.Timeline)
    private static final buffers.resources.TimelineOuterClass.Timeline DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new buffers.resources.TimelineOuterClass.Timeline();
    }

    public static buffers.resources.TimelineOuterClass.Timeline getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Timeline>
        PARSER = new com.google.protobuf.AbstractParser<Timeline>() {
      public Timeline parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Timeline(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Timeline> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Timeline> getParserForType() {
      return PARSER;
    }

    public buffers.resources.TimelineOuterClass.Timeline getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buffers_resources_Timeline_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buffers_resources_Timeline_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_buffers_resources_Timeline_Moment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_buffers_resources_Timeline_Moment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030resources/Timeline.proto\022\021buffers.reso" +
      "urces\032\roptions.proto\032\025resources/Event.pr" +
      "oto\"\271\001\n\010Timeline\022\014\n\004name\030\001 \001(\t\022\036\n\002id\030\002 \001" +
      "(\005B\022\202\265\030\016GMX_DEPRECATED\022>\n\007moments\030\003 \003(\0132" +
      "\".buffers.resources.Timeline.MomentB\t\202\265\030" +
      "\005entry\032?\n\006Moment\022\014\n\004step\030\001 \001(\005\022\'\n\005event\030" +
      "\002 \001(\0132\030.buffers.resources.Event"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          buffers.Options.getDescriptor(),
          buffers.resources.EventOuterClass.getDescriptor(),
        }, assigner);
    internal_static_buffers_resources_Timeline_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_buffers_resources_Timeline_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buffers_resources_Timeline_descriptor,
        new java.lang.String[] { "Name", "Id", "Moments", });
    internal_static_buffers_resources_Timeline_Moment_descriptor =
      internal_static_buffers_resources_Timeline_descriptor.getNestedTypes().get(0);
    internal_static_buffers_resources_Timeline_Moment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_buffers_resources_Timeline_Moment_descriptor,
        new java.lang.String[] { "Step", "Event", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(buffers.Options.gmx);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    buffers.Options.getDescriptor();
    buffers.resources.EventOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
